### ISSUE TITLE
Class 'yii\validators\ValidationAsset' not found

### ISSUE THREAD

**Issue by adiramardiani** [yii2tech/project-template#2]
I install this project template 2.0, but when access /signup or help/contact give
`Method yii\bootstrap\ActiveField::__toString() must not throw an exception, caught Error: Class 'yii\validators\ValidationAsset' not found`

In yii 2.1 this validator not exist ?

**Comment by klimov-paul** [comment]
This package does not refer to 'yii\validators\ValidationAsset' anywhere.
If you have problems using `yii\bootstrap\ActiveField` class, you should report it to [yiisoft/yii2-bootstrap](https://github.com/yiisoft/yii2-bootstrap) project.
